# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: pqgotest
      POSTGRES_USER: pqgotest

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080